/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package baleadas_intergalácticas;

import java.awt.event.KeyEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author megarokr
 */
public class StartScreen extends javax.swing.JFrame {

    /**
     * Creates new form StartScreen
     */
    public StartScreen() {
        initComponents();   
        this.setLocationRelativeTo(null);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_menu = new javax.swing.JDialog();
        tp_menu_options = new javax.swing.JTabbedPane();
        pane_lista_ordenes = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        JTableMenu = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        pane_agregar_menu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jt_tiempoPlato = new javax.swing.JTextField();
        jt_precioPlato = new javax.swing.JTextField();
        jt_nombrePlato = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jt_descripcionPlato = new javax.swing.JTextArea();
        btn_agregarPlato = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jt_cantidadIngredientesPlato = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jt_ingredientePlato = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jt_ingredienteMedida = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jt_ingredienteDescripcion = new javax.swing.JTextField();
        btn_agregarIngrediente = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jl_ingredientesPlato = new javax.swing.JList();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jt_nombrePlatoM = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jt_precioPlatoM = new javax.swing.JTextField();
        jt_tiempoPlatoM = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jt_descripcionPlatoM = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jt_ingredientePlatoM = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jt_cantidadIngredientesPlatoM = new javax.swing.JTextField();
        jt_ingredienteMedidaM = new javax.swing.JTextField();
        jt_ingredienteDescripcionM = new javax.swing.JTextField();
        btn_agregarIngredienteM = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jl_ingredientesPlatoM = new javax.swing.JList();
        jLabel20 = new javax.swing.JLabel();
        jc_menu = new javax.swing.JComboBox();
        btn_cargarPlato = new javax.swing.JButton();
        btn_guardarCambiosPlatos = new javax.swing.JButton();
        btn_eliminarIngrediente = new javax.swing.JButton();
        btn_cargarIngrediente = new javax.swing.JButton();
        jd_ingredients = new javax.swing.JDialog();
        lbl_nombre_ingrediente = new javax.swing.JLabel();
        lbl_cantidad_ingredientes = new javax.swing.JLabel();
        lbl_medida_ingredientes = new javax.swing.JLabel();
        lbl_descripcion_ingredientes = new javax.swing.JLabel();
        tf_nombreIngrediente = new javax.swing.JTextField();
        sp_cantidadIngrediente = new javax.swing.JSpinner();
        tf_medida_ingrediente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_descripcion_ingredientes = new javax.swing.JTextArea();
        agregar_ingrediente = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaTemp = new javax.swing.JList();
        jButton2 = new javax.swing.JButton();
        jd_order = new javax.swing.JDialog();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jl_menu = new javax.swing.JList();
        jScrollPane9 = new javax.swing.JScrollPane();
        jl_orden = new javax.swing.JList();
        cmd_agregarPlatoOrden = new javax.swing.JButton();
        cmd_ordenar = new javax.swing.JButton();
        tf_numOrden = new javax.swing.JTextField();
        tf_nombre_cliente = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jd_rrhh = new javax.swing.JDialog();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        jl_cocineros = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        js_hire = new javax.swing.JSpinner();
        js_fire = new javax.swing.JSpinner();
        cmd_hire = new javax.swing.JButton();
        cmd_fire = new javax.swing.JButton();
        jd_cierre = new javax.swing.JDialog();
        panel_buttons = new javax.swing.JPanel();
        cmd_menu = new javax.swing.JButton();
        cmd_ingredients = new javax.swing.JButton();
        cmd_order = new javax.swing.JButton();
        cmd_rrhh = new javax.swing.JButton();
        cmd_cierre = new javax.swing.JButton();
        lbl_meme = new javax.swing.JLabel();

        jd_menu.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                jd_menuWindowClosing(evt);
            }
        });

        tp_menu_options.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tp_menu_optionsStateChanged(evt);
            }
        });

        JTableMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número de Plato", "Nombre", "Precio", "Tiempo de Preparación"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(JTableMenu);

        jButton3.setText("Eliminar Elemento Seleccionado");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pane_lista_ordenesLayout = new javax.swing.GroupLayout(pane_lista_ordenes);
        pane_lista_ordenes.setLayout(pane_lista_ordenesLayout);
        pane_lista_ordenesLayout.setHorizontalGroup(
            pane_lista_ordenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pane_lista_ordenesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pane_lista_ordenesLayout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pane_lista_ordenesLayout.setVerticalGroup(
            pane_lista_ordenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_lista_ordenesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton3)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        tp_menu_options.addTab("Menu", pane_lista_ordenes);

        jLabel1.setText("Nombre:");

        jLabel2.setText("Precio:");

        jLabel3.setText("Tiempo de preparación:");

        jLabel4.setText("Descripción:");

        jt_descripcionPlato.setColumns(20);
        jt_descripcionPlato.setRows(5);
        jScrollPane3.setViewportView(jt_descripcionPlato);

        btn_agregarPlato.setText("Agregar Plato al Menú");
        btn_agregarPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarPlatoActionPerformed(evt);
            }
        });

        jLabel9.setText("Ingredientes Actuales");

        jLabel6.setText("Cantidad: ");

        jLabel7.setText("Medida");

        jLabel5.setText("Nombre:");

        jLabel8.setText("Descripción");

        btn_agregarIngrediente.setText("---->");
        btn_agregarIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarIngredienteActionPerformed(evt);
            }
        });

        jScrollPane4.setViewportView(jl_ingredientesPlato);

        jLabel10.setText("Agregar Ingredientes");

        javax.swing.GroupLayout pane_agregar_menuLayout = new javax.swing.GroupLayout(pane_agregar_menu);
        pane_agregar_menu.setLayout(pane_agregar_menuLayout);
        pane_agregar_menuLayout.setHorizontalGroup(
            pane_agregar_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_agregar_menuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pane_agregar_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pane_agregar_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pane_agregar_menuLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE))
                    .addGroup(pane_agregar_menuLayout.createSequentialGroup()
                        .addGroup(pane_agregar_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jt_tiempoPlato)
                            .addComponent(jt_precioPlato)
                            .addComponent(jt_nombrePlato, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_agregarPlato)))
                .addGap(28, 28, 28))
            .addGroup(pane_agregar_menuLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(81, 81, 81))
            .addGroup(pane_agregar_menuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pane_agregar_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pane_agregar_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jt_ingredientePlato, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt_cantidadIngredientesPlato, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pane_agregar_menuLayout.createSequentialGroup()
                        .addGroup(pane_agregar_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jt_ingredienteMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jt_ingredienteDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_agregarIngrediente)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pane_agregar_menuLayout.setVerticalGroup(
            pane_agregar_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_agregar_menuLayout.createSequentialGroup()
                .addGroup(pane_agregar_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pane_agregar_menuLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btn_agregarPlato))
                    .addGroup(pane_agregar_menuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pane_agregar_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jt_nombrePlato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pane_agregar_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jt_precioPlato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addGap(20, 20, 20)
                .addGroup(pane_agregar_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jt_tiempoPlato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGroup(pane_agregar_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pane_agregar_menuLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(pane_agregar_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)))
                    .addGroup(pane_agregar_menuLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(pane_agregar_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addGap(25, 25, 25)
                .addGroup(pane_agregar_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pane_agregar_menuLayout.createSequentialGroup()
                        .addGroup(pane_agregar_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jt_ingredientePlato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pane_agregar_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pane_agregar_menuLayout.createSequentialGroup()
                                .addComponent(jt_cantidadIngredientesPlato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(pane_agregar_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pane_agregar_menuLayout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(btn_agregarIngrediente))
                                    .addGroup(pane_agregar_menuLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(pane_agregar_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jt_ingredienteMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(pane_agregar_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jt_ingredienteDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jLabel6)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 58, Short.MAX_VALUE))
        );

        tp_menu_options.addTab("Agregar", pane_agregar_menu);

        jLabel11.setText("Nombre:");

        jLabel12.setText("Precio:");

        jLabel13.setText("Tiempo de preparación:");

        jLabel14.setText("Descripción:");

        jt_descripcionPlatoM.setColumns(20);
        jt_descripcionPlatoM.setRows(5);
        jScrollPane6.setViewportView(jt_descripcionPlatoM);

        jLabel15.setText("Agregar Ingredientes");

        jLabel16.setText("Nombre:");

        jLabel17.setText("Cantidad: ");

        jLabel18.setText("Medida");

        jLabel19.setText("Descripción");

        btn_agregarIngredienteM.setText("---->");
        btn_agregarIngredienteM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarIngredienteMActionPerformed(evt);
            }
        });

        jScrollPane7.setViewportView(jl_ingredientesPlatoM);

        jLabel20.setText("Ingredientes Actuales");

        btn_cargarPlato.setText("Cargar Plato");
        btn_cargarPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cargarPlatoActionPerformed(evt);
            }
        });

        btn_guardarCambiosPlatos.setText("Guardar Cambios");
        btn_guardarCambiosPlatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarCambiosPlatosActionPerformed(evt);
            }
        });

        btn_eliminarIngrediente.setText("Eliminar Ingrediente Seleccionado");
        btn_eliminarIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarIngredienteActionPerformed(evt);
            }
        });

        btn_cargarIngrediente.setText("Cargar Ingrediente Seleccionado");
        btn_cargarIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cargarIngredienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(btn_guardarCambiosPlatos, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jc_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jt_tiempoPlatoM)
                                    .addComponent(jt_precioPlatoM)
                                    .addComponent(jt_nombrePlatoM, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_cargarPlato)
                                .addGap(59, 59, 59))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel17))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jt_ingredientePlatoM, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jt_cantidadIngredientesPlatoM, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jt_ingredienteMedidaM, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jt_ingredienteDescripcionM, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addComponent(btn_agregarIngredienteM))
                            .addComponent(btn_cargarIngrediente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(btn_eliminarIngrediente)))))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jt_nombrePlatoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jc_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jt_precioPlatoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12))
                    .addComponent(btn_cargarPlato))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jt_tiempoPlatoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(btn_guardarCambiosPlatos)
                        .addGap(106, 106, 106)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel20))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(btn_agregarIngredienteM))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_eliminarIngrediente)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btn_cargarIngrediente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jt_ingredientePlatoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jt_cantidadIngredientesPlatoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jt_ingredienteMedidaM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jt_ingredienteDescripcionM, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18)))
                        .addGap(20, 20, 20))))
        );

        tp_menu_options.addTab("Modificar", jPanel1);

        javax.swing.GroupLayout jd_menuLayout = new javax.swing.GroupLayout(jd_menu.getContentPane());
        jd_menu.getContentPane().setLayout(jd_menuLayout);
        jd_menuLayout.setHorizontalGroup(
            jd_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_menuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tp_menu_options)
                .addContainerGap())
        );
        jd_menuLayout.setVerticalGroup(
            jd_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_menuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tp_menu_options)
                .addContainerGap())
        );

        jd_ingredients.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jd_ingredients.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jd_ingredients.setMinimumSize(new java.awt.Dimension(720, 320));
        jd_ingredients.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                jd_ingredientsWindowClosing(evt);
            }
        });

        lbl_nombre_ingrediente.setText("Nombre: ");

        lbl_cantidad_ingredientes.setText("Cantidad: ");

        lbl_medida_ingredientes.setText("Medida:");

        lbl_descripcion_ingredientes.setText("Descripción: ");

        sp_cantidadIngrediente.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(1.0d), Double.valueOf(0.5d), null, Double.valueOf(0.5d)));

        ta_descripcion_ingredientes.setColumns(20);
        ta_descripcion_ingredientes.setRows(5);
        jScrollPane1.setViewportView(ta_descripcion_ingredientes);

        agregar_ingrediente.setText("Agregar");
        agregar_ingrediente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregar_ingredienteMouseClicked(evt);
            }
        });

        jScrollPane2.setViewportView(listaTemp);

        jButton2.setText("refresh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_ingredientsLayout = new javax.swing.GroupLayout(jd_ingredients.getContentPane());
        jd_ingredients.getContentPane().setLayout(jd_ingredientsLayout);
        jd_ingredientsLayout.setHorizontalGroup(
            jd_ingredientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_ingredientsLayout.createSequentialGroup()
                .addGroup(jd_ingredientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_ingredientsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jd_ingredientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_nombre_ingrediente)
                            .addComponent(lbl_cantidad_ingredientes)
                            .addComponent(lbl_medida_ingredientes)
                            .addComponent(lbl_descripcion_ingredientes))
                        .addGap(23, 23, 23)
                        .addGroup(jd_ingredientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jd_ingredientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tf_nombreIngrediente)
                                .addComponent(sp_cantidadIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tf_medida_ingrediente, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))))
                    .addGroup(jd_ingredientsLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(agregar_ingrediente)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addGroup(jd_ingredientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap())
        );
        jd_ingredientsLayout.setVerticalGroup(
            jd_ingredientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ingredientsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_ingredientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nombre_ingrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_nombreIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jd_ingredientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_ingredientsLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jd_ingredientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_cantidad_ingredientes)
                            .addComponent(sp_cantidadIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jd_ingredientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_medida_ingredientes)
                            .addComponent(tf_medida_ingrediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jd_ingredientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_descripcion_ingredientes)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(agregar_ingrediente))
                    .addGroup(jd_ingredientsLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jd_order.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                jd_orderWindowClosing(evt);
            }
        });

        jLabel21.setText("Número de orden: ");

        jLabel22.setText("Nombre de cliente:");

        jLabel23.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel23.setText("Menú");

        jScrollPane8.setViewportView(jl_menu);

        jl_orden.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jl_ordenKeyPressed(evt);
            }
        });
        jScrollPane9.setViewportView(jl_orden);

        cmd_agregarPlatoOrden.setText("------->");
        cmd_agregarPlatoOrden.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmd_agregarPlatoOrdenMouseClicked(evt);
            }
        });

        cmd_ordenar.setText("Ordenar");
        cmd_ordenar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmd_ordenarMouseClicked(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel27.setText("Platos Actuales");

        javax.swing.GroupLayout jd_orderLayout = new javax.swing.GroupLayout(jd_order.getContentPane());
        jd_order.getContentPane().setLayout(jd_orderLayout);
        jd_orderLayout.setHorizontalGroup(
            jd_orderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_orderLayout.createSequentialGroup()
                .addGroup(jd_orderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_orderLayout.createSequentialGroup()
                        .addContainerGap(132, Short.MAX_VALUE)
                        .addGroup(jd_orderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jd_orderLayout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_nombre_cliente))
                            .addGroup(jd_orderLayout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_numOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(116, 116, 116))
                    .addGroup(jd_orderLayout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(cmd_ordenar, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jd_orderLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmd_agregarPlatoOrden)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jd_orderLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel27)
                .addGap(49, 49, 49))
        );
        jd_orderLayout.setVerticalGroup(
            jd_orderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_orderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_orderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(tf_numOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_orderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(tf_nombre_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jd_orderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_orderLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(cmd_agregarPlatoOrden)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_orderLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addGroup(jd_orderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_orderLayout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_orderLayout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(12, 12, 12)
                .addComponent(cmd_ordenar)
                .addGap(26, 26, 26))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número de orden", "Progress", "Remaining"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane10.setViewportView(jTable1);

        jLabel24.setText("Número de cocineros:");

        jLabel25.setText("Contratar:");

        jLabel26.setText("Despedir:");

        cmd_hire.setText("Contratar");

        cmd_fire.setText("Despedir");

        javax.swing.GroupLayout jd_rrhhLayout = new javax.swing.GroupLayout(jd_rrhh.getContentPane());
        jd_rrhh.getContentPane().setLayout(jd_rrhhLayout);
        jd_rrhhLayout.setHorizontalGroup(
            jd_rrhhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_rrhhLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_rrhhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_rrhhLayout.createSequentialGroup()
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 2, Short.MAX_VALUE))
                    .addGroup(jd_rrhhLayout.createSequentialGroup()
                        .addGroup(jd_rrhhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jd_rrhhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jl_cocineros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(js_hire, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                            .addComponent(js_fire))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jd_rrhhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmd_hire, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmd_fire, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jd_rrhhLayout.setVerticalGroup(
            jd_rrhhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_rrhhLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_rrhhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jl_cocineros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_rrhhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(js_hire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmd_hire))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_rrhhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(js_fire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmd_fire))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jd_cierreLayout = new javax.swing.GroupLayout(jd_cierre.getContentPane());
        jd_cierre.getContentPane().setLayout(jd_cierreLayout);
        jd_cierreLayout.setHorizontalGroup(
            jd_cierreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jd_cierreLayout.setVerticalGroup(
            jd_cierreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmd_menu.setText("Menú");
        cmd_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmd_menuMouseClicked(evt);
            }
        });
        cmd_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_menuActionPerformed(evt);
            }
        });

        cmd_ingredients.setText("Ingredientes");
        cmd_ingredients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmd_ingredientsMouseClicked(evt);
            }
        });

        cmd_order.setText("Ordenar");
        cmd_order.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmd_orderMouseClicked(evt);
            }
        });

        cmd_rrhh.setText("RRHH");

        cmd_cierre.setText("Cierre del día");

        javax.swing.GroupLayout panel_buttonsLayout = new javax.swing.GroupLayout(panel_buttons);
        panel_buttons.setLayout(panel_buttonsLayout);
        panel_buttonsLayout.setHorizontalGroup(
            panel_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_buttonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmd_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmd_order, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmd_rrhh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmd_cierre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmd_ingredients, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panel_buttonsLayout.setVerticalGroup(
            panel_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_buttonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmd_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmd_ingredients, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmd_order, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmd_rrhh, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmd_cierre, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        lbl_meme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baleadas_intergalácticas/resources/baleadas.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_buttons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_meme)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_buttons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_meme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmd_ingredientsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmd_ingredientsMouseClicked
        this.setVisible(false);
        openDialog(jd_ingredients);
        
    }//GEN-LAST:event_cmd_ingredientsMouseClicked

    private void agregar_ingredienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregar_ingredienteMouseClicked
        String nombre, medida, descripcion;
        double cantidad;

        if(tf_nombreIngrediente.getText() != null && tf_medida_ingrediente.getText() != null && (Double)sp_cantidadIngrediente.getValue() >= 0 && ta_descripcion_ingredientes.getText() != null){        
            nombre = tf_nombreIngrediente.getText();
            tf_nombreIngrediente.setText("");
            medida = tf_medida_ingrediente.getText();
            tf_medida_ingrediente.setText("");
            cantidad = (Double)sp_cantidadIngrediente.getValue();
            sp_cantidadIngrediente.setValue(0.5);
            descripcion = ta_descripcion_ingredientes.getText();
            ta_descripcion_ingredientes.setText("");
            
            if(almacen.size() > 0){
                for (int i = 0; i < almacen.size(); ++i) {
                    if(((Ingrediente)((Stack)almacen.elementAt(i).getValue()).peek()).getNombre().equalsIgnoreCase(nombre)){
                        ((Stack)almacen.elementAt(i).getValue()).push_back(new Ingrediente(nombre, cantidad, medida, descripcion));
                        break;
                    }
                    else if(i == almacen.size()-1){
                        almacen.push_back(new Stack(new Ingrediente(nombre, cantidad, medida, descripcion)));
                        break;
                    }
                }
            } else {
                almacen.push_back(new Stack(new Ingrediente(nombre, cantidad, medida, descripcion)));
            }
            
            
                
        } else {
            JOptionPane.showMessageDialog(jd_ingredients, "Hay un campo en blanco.", "Campo en blanco", JOptionPane.ERROR_MESSAGE, null);
        }
    }//GEN-LAST:event_agregar_ingredienteMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultListModel model = new DefaultListModel();
        Ingrediente ingrediente;
        Stack stack;
        String string;
        for (int i = 0; i < almacen.size(); i++) {
            stack = (Stack)almacen.elementAt(i).getValue();
            ingrediente = (Ingrediente)stack.peek();
            string = ingrediente.toString();
            model.add(i, string);
        }
        this.listaTemp.setModel(model);       
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jd_ingredientsWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jd_ingredientsWindowClosing
        jd_ingredients.dispose(); //Que malote
        this.setVisible(true);
    }//GEN-LAST:event_jd_ingredientsWindowClosing

    private void cmd_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmd_menuMouseClicked
        this.setVisible(false);
        openDialog(jd_menu);
    }//GEN-LAST:event_cmd_menuMouseClicked

    private void cmd_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_menuActionPerformed
        this.setVisible(false);
        this.openDialog(jd_menu);
        
    }//GEN-LAST:event_cmd_menuActionPerformed

    private void btn_agregarPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarPlatoActionPerformed
        String nombre,descripcion;
        double precio;
        int tiempoPreparacion;
        
        if (!isNumber(jt_tiempoPlato.getText()) || !isNumber(jt_precioPlato.getText())){
            JOptionPane.showMessageDialog(this, "Ingreso un valor no numérico en un campo","Error", JOptionPane.ERROR_MESSAGE);
            
        }else{
            if ((jt_nombrePlato.getText()==null || jt_nombrePlato.getText().equals("") )
                    || (jt_descripcionPlato.getText()==null || jt_descripcionPlato.getText().equals("")) 
                    || (jt_tiempoPlato.getText()==null || jt_tiempoPlato.getText().equals("")
                    || (jt_precioPlato.getText()==null || jt_precioPlato.getText().equals(""))) 
                    || this.ingredientesTemp.size()==0){

                JOptionPane.showMessageDialog(this, "Valor inválido en algún campo o la lista de ingredientes está vacía", "Error", JOptionPane.ERROR_MESSAGE);

            }else{
                nombre = jt_nombrePlato.getText();
                descripcion = jt_descripcionPlato.getText();
                precio = Double.parseDouble(jt_precioPlato.getText());
                tiempoPreparacion = Integer.parseInt(jt_tiempoPlato.getText());
                menu.push_back(new Plato(nombre,descripcion,precio,tiempoPreparacion,ingredientesTemp));

                jt_nombrePlato.setText("");
                jt_descripcionPlato.setText("");
                jt_tiempoPlato.setText("");
                jt_precioPlato.setText("");
                ingredientesTemp = new List();

                jl_ingredientesPlato.setModel(new DefaultListModel());
                JOptionPane.showMessageDialog(this, "Plato agregado con éxito", "Confirmación", JOptionPane.INFORMATION_MESSAGE);

                reloadTable();

            }
        }
  
    }//GEN-LAST:event_btn_agregarPlatoActionPerformed

    private void btn_agregarIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarIngredienteActionPerformed
        
        
        if (!isNumber(jt_cantidadIngredientesPlato.getText())){
            JOptionPane.showMessageDialog(this, "Ingreso un valor no numérico en un campo","Error", JOptionPane.ERROR_MESSAGE);
        }else{
            if ((jt_ingredientePlato.getText() == null || jt_ingredientePlato.getText().equals("")) 
                || (jt_cantidadIngredientesPlato.getText()==null || jt_cantidadIngredientesPlato.getText().equals(""))
                || (jt_ingredienteDescripcion.getText()==null || jt_ingredienteDescripcion.getText().equals(""))
                || (jt_ingredienteMedida.getText()==null || jt_ingredienteMedida.getText().equals("")) ) {
            
            JOptionPane.showMessageDialog(this, "Valor invalido en algun campo", "Error", JOptionPane.ERROR_MESSAGE);
            
        }else{
            ingredientesTemp.push_back(new Ingrediente(jt_ingredientePlato.getText()
                    ,Double.parseDouble(jt_cantidadIngredientesPlato.getText())
                    ,jt_ingredienteMedida.getText()
                    ,jt_ingredienteDescripcion.getText()));
            DefaultListModel model = new DefaultListModel();
            for (int i = 0; i < ingredientesTemp.size(); i++) {
                model.add(i,((Ingrediente)ingredientesTemp.elementAt(i).getValue()).toString());
            }
            jl_ingredientesPlato.setModel(model);
            jt_ingredientePlato.setText("");
            jt_cantidadIngredientesPlato.setText("");
            jt_ingredienteDescripcion.setText("");
            jt_ingredienteMedida.setText("");
            }
        }
        
        
        
        
        
    }//GEN-LAST:event_btn_agregarIngredienteActionPerformed

    private void jd_menuWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jd_menuWindowClosing
       jd_menu.dispose();
       this.setVisible(true);
    }//GEN-LAST:event_jd_menuWindowClosing

    private void btn_agregarIngredienteMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarIngredienteMActionPerformed
        if (!isNumber(jt_cantidadIngredientesPlatoM.getText())){
            JOptionPane.showMessageDialog(this, "Ingreso un valor no numérico en un campo","Error", JOptionPane.ERROR_MESSAGE);
        }else{
            if ((jt_ingredientePlatoM.getText() == null || jt_ingredientePlatoM.getText().equals("")) 
                || (jt_cantidadIngredientesPlatoM.getText()==null || jt_cantidadIngredientesPlatoM.getText().equals(""))
                || (jt_ingredienteDescripcionM.getText()==null || jt_ingredienteDescripcionM.getText().equals(""))
                || (jt_ingredienteMedidaM.getText()==null || jt_ingredienteMedidaM.getText().equals("")) ) {
            
            JOptionPane.showMessageDialog(this, "Valor invalido en algun campo", "Error", JOptionPane.ERROR_MESSAGE);
            
        }else{
            ingredientesTemp.push_back(new Ingrediente(jt_ingredientePlatoM.getText()
                    ,Double.parseDouble(jt_cantidadIngredientesPlatoM.getText())
                    ,jt_ingredienteMedidaM.getText()
                    ,jt_ingredienteDescripcionM.getText()));
            DefaultListModel model = new DefaultListModel();
            for (int i = 0; i < ingredientesTemp.size(); i++) {
                model.add(i,((Ingrediente)ingredientesTemp.elementAt(i).getValue()).toString());
            }
            jl_ingredientesPlatoM.setModel(model);
            jt_ingredientePlatoM.setText("");
            jt_cantidadIngredientesPlatoM.setText("");
            jt_ingredienteDescripcionM.setText("");
            jt_ingredienteMedidaM.setText("");
            }
        }
    }//GEN-LAST:event_btn_agregarIngredienteMActionPerformed

    private void tp_menu_optionsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tp_menu_optionsStateChanged
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        
        for (int i = 0; i < menu.size(); i++) {
            model.addElement(((Plato)menu.elementAt(i).getValue()).getNombre());
        }
        jc_menu.setModel(model);
    }//GEN-LAST:event_tp_menu_optionsStateChanged

    private void btn_cargarPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cargarPlatoActionPerformed
        menuIndex = jc_menu.getSelectedIndex();
        this.jt_nombrePlatoM.setText(((Plato)menu.elementAt(menuIndex).getValue()).getNombre());
        this.jt_precioPlatoM.setText(Double.toString(((Plato)menu.elementAt(menuIndex).getValue()).getPrecio()));
        this.jt_tiempoPlatoM.setText(Integer.toString(((Plato)menu.elementAt(menuIndex).getValue()).getPreparacion()));
        this.jt_descripcionPlatoM.setText(((Plato)menu.elementAt(menuIndex).getValue()).getDescripcion());
        
        DefaultListModel model = new DefaultListModel();
            for (int i = 0; i < ((Plato)menu.elementAt(menuIndex).getValue()).getIngredientes().size(); i++) {
                model.add(i,(((Plato)menu.elementAt(menuIndex).getValue()).getIngredientes().elementAt(i).getValue()).toString());
            }
        jl_ingredientesPlatoM.setModel(model);
        ingredientesTemp = ((Plato)menu.elementAt(menuIndex).getValue()).getIngredientes();
    }//GEN-LAST:event_btn_cargarPlatoActionPerformed

    private void btn_cargarIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cargarIngredienteActionPerformed
        int index = jl_ingredientesPlatoM.getSelectedIndex();
        if (index !=-1){
            jt_ingredientePlatoM.setText(((Ingrediente)ingredientesTemp.elementAt(index).getValue()).getNombre());
            jt_cantidadIngredientesPlatoM.setText(Double.toString(((Ingrediente)ingredientesTemp.elementAt(index).getValue()).getCantidad()));
            jt_ingredienteMedidaM.setText(((Ingrediente)ingredientesTemp.elementAt(index).getValue()).getMedida());
            jt_ingredienteDescripcionM.setText(((Ingrediente)ingredientesTemp.elementAt(index).getValue()).getDescripción());
        }else{
            JOptionPane.showMessageDialog(this, "Porfavor seleccione un elemento de la lista", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btn_cargarIngredienteActionPerformed

    private void btn_eliminarIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarIngredienteActionPerformed
        int index = jl_ingredientesPlatoM.getSelectedIndex();
        if (index!=-1){
            ingredientesTemp.remove(index);
            DefaultListModel model = new DefaultListModel();
            for (int i = 0; i < ingredientesTemp.size(); i++) {
                model.add(i,((Ingrediente)ingredientesTemp.elementAt(i).getValue()).toString());
            }
            jl_ingredientesPlatoM.setModel(model);
            
            
        } else{
            JOptionPane.showMessageDialog(this, "Porfavor seleccione un elemento de la lista de ingredientes", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_eliminarIngredienteActionPerformed

    private void btn_guardarCambiosPlatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarCambiosPlatosActionPerformed
        String nombre,descripcion;
        double precio;
        int tiempoPreparacion;
        
        if (!isNumber(jt_tiempoPlatoM.getText()) || !isNumber(jt_precioPlatoM.getText())){
            JOptionPane.showMessageDialog(this, "Ingreso un valor no numérico en un campo","Error", JOptionPane.ERROR_MESSAGE);
            
        }else{
            if ((jt_nombrePlatoM.getText()==null || jt_nombrePlatoM.getText().equals("") )
                    || (jt_descripcionPlatoM.getText()==null || jt_descripcionPlatoM.getText().equals("")) 
                    || (jt_tiempoPlatoM.getText()==null || jt_tiempoPlatoM.getText().equals("")
                    || (jt_precioPlatoM.getText()==null || jt_precioPlatoM.getText().equals(""))) 
                    || this.ingredientesTemp.size()==0){

                JOptionPane.showMessageDialog(this, "Valor inválido en algún campo o la lista de ingredientes está vacía", "Error", JOptionPane.ERROR_MESSAGE);

            }else{
                nombre = jt_nombrePlatoM.getText();
                descripcion = jt_descripcionPlatoM.getText();
                precio = Double.parseDouble(jt_precioPlatoM.getText());
                tiempoPreparacion = Integer.parseInt(jt_tiempoPlatoM.getText());
                menu.remove(menuIndex);
                menu.push_back(new Plato(nombre,descripcion,precio,tiempoPreparacion,ingredientesTemp));

                jt_nombrePlatoM.setText("");
                jt_descripcionPlatoM.setText("");
                jt_tiempoPlatoM.setText("");
                jt_precioPlatoM.setText("");
                ingredientesTemp = new List();

                jl_ingredientesPlatoM.setModel(new DefaultListModel());
                JOptionPane.showMessageDialog(this, "Plato agregado con éxito", "Confirmación", JOptionPane.INFORMATION_MESSAGE);

                reloadTable();
                DefaultComboBoxModel comboBoxModel = new DefaultComboBoxModel();
                for (int i = 0; i < menu.size(); i++) {
                    comboBoxModel.addElement(((Plato)menu.elementAt(i).getValue()).getNombre());
                }
                jc_menu.setModel(comboBoxModel);

            }
        }
    }//GEN-LAST:event_btn_guardarCambiosPlatosActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int index = this.JTableMenu.getSelectedRow();
        if (index !=-1){
            menu.remove(index);
            reloadTable();
        }else{
            JOptionPane.showMessageDialog(this, "Porvafor seleccione un elemento de la tabla", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cmd_orderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmd_orderMouseClicked
        this.setVisible(false);
        DefaultListModel modelo = new DefaultListModel();
        for(int i = 0; i < menu.size(); ++i){
            modelo.addElement((Plato)menu.elementAt(i).getValue());
        }
        jl_menu.setModel(modelo);
        this.openDialog(jd_order);
    }//GEN-LAST:event_cmd_orderMouseClicked

    private void cmd_agregarPlatoOrdenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmd_agregarPlatoOrdenMouseClicked
        int index = jl_menu.getSelectedIndex();
        
        if (index !=-1){
            Object selection = jl_menu.getSelectedValue();
            DefaultListModel modelo = new DefaultListModel();
            for (int i = 0; i < platosTemp.size(); i++) {
                modelo.addElement(platosTemp.elementAt(i));
            }
            modelo.addElement((Plato)selection);
            platosTemp.push_back(selection);
            jl_orden.setModel(modelo);
        }else{
            JOptionPane.showMessageDialog(this, "Porfavor seleccione un elemento de la lista", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_cmd_agregarPlatoOrdenMouseClicked

    private void jl_ordenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jl_ordenKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_DELETE || evt.getKeyCode() == KeyEvent.VK_BACK_SPACE){
            int index = jl_orden.getSelectedIndex();
            if (index!=-1){
                DefaultListModel modelo = (DefaultListModel)jl_orden.getModel();
                modelo.remove(index);
                jl_orden.setModel(modelo);
            }else{
                JOptionPane.showMessageDialog(this, "Porvafor seleccione un elemento de la lista", "Error", JOptionPane.ERROR_MESSAGE);
            }
                
        }
    }//GEN-LAST:event_jl_ordenKeyPressed

    private void cmd_ordenarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmd_ordenarMouseClicked
        DefaultListModel modelo = new DefaultListModel();
        for (int i = 0; i < platosTemp.size(); i++) {
            modelo.addElement(platosTemp.elementAt(i));
        }
        if((tf_numOrden.getText() != null && !tf_nombre_cliente.getText().equals("")) && (tf_nombre_cliente.getText() != null && !tf_nombre_cliente.getText().equals("")) && !modelo.isEmpty()){
            if(isNumber(tf_numOrden.getText())){
                Orden temp = new Orden(Integer.parseInt(tf_numOrden.getText()),tf_nombre_cliente.getText(),platosTemp);
                int selection = JOptionPane.showConfirmDialog(this, temp.toString(), "Orden", JOptionPane.OK_CANCEL_OPTION);
                
                if(selection == JOptionPane.OK_OPTION){
                    ordenes.queue(temp);
                    tf_numOrden.setText("");
                    tf_nombre_cliente.setText("");
                    modelo.clear();
                    platosTemp = new List();
                    jl_orden.setModel(modelo);
                }
            }
            else{
                JOptionPane.showMessageDialog(this, "Ingreso un valor no numérico en un campo","Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Hay campos vacíos","Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cmd_ordenarMouseClicked

    private void jd_orderWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jd_orderWindowClosing
        jd_order.dispose();
       this.setVisible(true);
    }//GEN-LAST:event_jd_orderWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK+".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartScreen().setVisible(true);
            }
        });
    }
    
    private void openDialog(javax.swing.JDialog jd_ventana){
        jd_ventana.setLocationRelativeTo(this);
        jd_ventana.setModal(true);
        jd_ventana.pack();
        jd_ventana.setVisible(true);
        
    }
    private void reloadTable(){
        DefaultTableModel tableModel = (DefaultTableModel)JTableMenu.getModel();
        
        while(tableModel.getRowCount()!=0){
            tableModel.removeRow(0);
        }

        Object row[];
        for (int i = 0; i < menu.size(); i++) {
            row = new Object[]{(i+1)
                    ,((Plato)menu.elementAt(i).getValue()).getNombre()
                    ,((Plato)menu.elementAt(i).getValue()).getPrecio()
                    ,((Plato)menu.elementAt(i).getValue()).getPreparacion()};
            tableModel.addRow(row);

        }
        JTableMenu.setModel(tableModel);
    }
    
    private boolean isNumber(String string){
        int contador = 0;
        
        for (int i = 0; i < string.length(); i++) {
            if (string.charAt(i) == '0'
                    || string.charAt(i) == '1'
                    || string.charAt(i) == '2'
                    || string.charAt(i) == '3'
                    || string.charAt(i) == '4'
                    || string.charAt(i) == '5'
                    || string.charAt(i) == '6'
                    || string.charAt(i) == '7'
                    || string.charAt(i) == '8'
                    || string.charAt(i) == '9'
                    || string.charAt(i) == '.'){
                if (string.charAt(i) == '.'){
                    contador++;
                }
            } else{
                return false;
            }
        }
        if(contador>1){
            return false;
        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTableMenu;
    private javax.swing.JButton agregar_ingrediente;
    private javax.swing.JButton btn_agregarIngrediente;
    private javax.swing.JButton btn_agregarIngredienteM;
    private javax.swing.JButton btn_agregarPlato;
    private javax.swing.JButton btn_cargarIngrediente;
    private javax.swing.JButton btn_cargarPlato;
    private javax.swing.JButton btn_eliminarIngrediente;
    private javax.swing.JButton btn_guardarCambiosPlatos;
    private javax.swing.JButton cmd_agregarPlatoOrden;
    private javax.swing.JButton cmd_cierre;
    private javax.swing.JButton cmd_fire;
    private javax.swing.JButton cmd_hire;
    private javax.swing.JButton cmd_ingredients;
    private javax.swing.JButton cmd_menu;
    private javax.swing.JButton cmd_ordenar;
    private javax.swing.JButton cmd_order;
    private javax.swing.JButton cmd_rrhh;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox jc_menu;
    private javax.swing.JDialog jd_cierre;
    private javax.swing.JDialog jd_ingredients;
    private javax.swing.JDialog jd_menu;
    private javax.swing.JDialog jd_order;
    private javax.swing.JDialog jd_rrhh;
    private javax.swing.JLabel jl_cocineros;
    private javax.swing.JList jl_ingredientesPlato;
    private javax.swing.JList jl_ingredientesPlatoM;
    private javax.swing.JList jl_menu;
    private javax.swing.JList jl_orden;
    private javax.swing.JSpinner js_fire;
    private javax.swing.JSpinner js_hire;
    private javax.swing.JTextField jt_cantidadIngredientesPlato;
    private javax.swing.JTextField jt_cantidadIngredientesPlatoM;
    private javax.swing.JTextArea jt_descripcionPlato;
    private javax.swing.JTextArea jt_descripcionPlatoM;
    private javax.swing.JTextField jt_ingredienteDescripcion;
    private javax.swing.JTextField jt_ingredienteDescripcionM;
    private javax.swing.JTextField jt_ingredienteMedida;
    private javax.swing.JTextField jt_ingredienteMedidaM;
    private javax.swing.JTextField jt_ingredientePlato;
    private javax.swing.JTextField jt_ingredientePlatoM;
    private javax.swing.JTextField jt_nombrePlato;
    private javax.swing.JTextField jt_nombrePlatoM;
    private javax.swing.JTextField jt_precioPlato;
    private javax.swing.JTextField jt_precioPlatoM;
    private javax.swing.JTextField jt_tiempoPlato;
    private javax.swing.JTextField jt_tiempoPlatoM;
    private javax.swing.JLabel lbl_cantidad_ingredientes;
    private javax.swing.JLabel lbl_descripcion_ingredientes;
    private javax.swing.JLabel lbl_medida_ingredientes;
    private javax.swing.JLabel lbl_meme;
    private javax.swing.JLabel lbl_nombre_ingrediente;
    private javax.swing.JList listaTemp;
    private javax.swing.JPanel pane_agregar_menu;
    private javax.swing.JPanel pane_lista_ordenes;
    private javax.swing.JPanel panel_buttons;
    private javax.swing.JSpinner sp_cantidadIngrediente;
    private javax.swing.JTextArea ta_descripcion_ingredientes;
    private javax.swing.JTextField tf_medida_ingrediente;
    private javax.swing.JTextField tf_nombreIngrediente;
    private javax.swing.JTextField tf_nombre_cliente;
    private javax.swing.JTextField tf_numOrden;
    private javax.swing.JTabbedPane tp_menu_options;
    // End of variables declaration//GEN-END:variables
    private List almacen= new List();
    private List menu = new List();
    private List ingredientesTemp = new List();
    private List platosTemp = new List();
    private Queue ordenes = new Queue();
    private Queue cocineros = new Queue();
    private int menuIndex;

}
